### ISSUE TITLE
Map is not the best method in this case because you are not using the return value

### ISSUE THREAD

**Issue by ThiagoBfim** [renanalvesdev/java-backend-challenge#1]
Map receives a Consumer.

Prefer to use ifPresentOrElse method :)

https://github.com/renanalvesdev/java-backend-challenge/blob/40fb97ba233a0f7e6d02c53d337724bb0715d50f/src/main/java/pt/com/renan/javabechallenge/service/impl/UserServiceImpl.java#L67

**Comment by renanalvesdev** [comment]
corrected
